MVC3Site.UI.MVC/Controllers/AuthorsController.cs
using MVC3Site.DATA.EF;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVC3Site.UI.MVC.Controllers
{
    public class AuthorsController : Controller
    {
        private BookStorePlusEntities db = new BookStorePlusEntities();

        // GET: Authors
        public ActionResult Index(string searchFilter)
        {
            //searchfilter represents the textbox (search info from the user) in the index view.
            //if search box is empty - return ALL authors
            if (string.IsNullOrEmpty(searchFilter))
            {
                return View(db.Authors.ToList());
            }
            else
            //check the search box and return values that match first or last name.  Fuzzy search not an exact match
            {
                var searchResults = db.Authors.Where(a => a.FirstName.ToLower().Contains(searchFilter.ToLower()) ||
                a.LastName.ToLower().Contains(searchFilter.ToLower())).OrderBy(a => a.FirstName).ThenBy(a => a.LastName);
                return View(searchResults);
                
            }

        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,FirstName,LastName,City,State,ZipCode,Country")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,FirstName,LastName,City,State,ZipCode,Country")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC3Site.UI.MVC/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC3Site.DATA.EF;
using PagedList;
using PagedList.Mvc;
using MVC3Site.UI.MVC.Models;//ShoppingCartViewModel

namespace MVC3Site.UI.MVC.Controllers
{
    //[Authorize(Roles ="Admin")] //--Disallows everyone EXCEPT admin
    //[Authorize]//-No Anonymous users are allowed to ANY of the actions/views
    public class BooksController : Controller
    {
        private BookStorePlusEntities db = new BookStorePlusEntities();

        #region AddToCart (Shopping Cart Functionality)
        [HttpPost]
        public ActionResult AddToCart(int qty, int bookID)
        {
            //Create and Empty shopping cart (local version)
            Dictionary<int, ShoppingCartViewModel> shoppingCart = null;

            //check the session variable that represents a cart with items in it
            //if the global cart has "stuff" in it, then we will assign its value to our local version.
            if (Session["cart"] != null)
            {
                shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];
            }
            //else - create an empty local version
            else
            {
                shoppingCart = new Dictionary<int, ShoppingCartViewModel>();
            }

            //Get the product being added (using the id)
            Book product = db.Books.Where(b => b.BookID == bookID).FirstOrDefault();

            //if the product is null - redirect to the books index
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            //else - Add the product and quantity to the cart
            else
            {
                //Create the ShoppingCartViewModel object
                ShoppingCartViewModel item = new ShoppingCartViewModel(qty, product);

                //if the shoppingcart already has a product with that id, increase the qty (local)
                if (shoppingCart.ContainsKey(product.BookID))
                {
                    shoppingCart[product.BookID].Qty += qty;
                }
                //else add it to the cart (local)
                else
                {
                    shoppingCart.Add(product.BookID, item);
                }

                //update the global cart (session) with the NEW information
                Session["cart"] = shoppingCart;

            }
            //send the user to the shopping cart landing page (index)
            return RedirectToAction("Index", "ShoppingCart");
        }


        #endregion

        //[AllowAnonymous]//ONLY allows Anonymous users no specific roles - If the Admin authorize is up top, then
        //customer Role people will NOT have access
        // GET: Books
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.BookRoyalty).Include(b => b.BookStatus).Include(b => b.Genre).Include(b => b.Publisher);
            return View(books.ToList());
        }

        //New Action to handle paging by itself.
        //Default to page 1 in the parameter set
        public ActionResult BooksPaging(int page=1)
        {
            //set the page size - this could be done with a querystring and let the user select the page size
            //(how many rows in the table per page)
            int pageSize = 7;

            //This is the same query used in the Index Action.
            //for PagedList to work, the OrderBy() (or keyword depending on your syntax) MUST be included in the query
            //The pagedList is dependent on the results being ordered.
            var books = db.Books.Include(b => b.BookRoyalty)
                                .Include(b => b.BookStatus)
                                .Include(b => b.Genre)
                                .Include(b => b.Publisher)
                                .OrderBy(b=>b.BookTitle);//***** ORDERBY for Paging *****


            return View(books.ToPagedList(page,pageSize));
        }
        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [Authorize(Roles ="Admin")]
        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.BookID = new SelectList(db.BookRoyalties, "BookID", "BookID");
            ViewBag.BookStatusID = new SelectList(db.BookStatuses, "BookStatusID", "BookStatusName");
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName");
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookID,ISBN,BookTitle,Description,GenreID,Price,UnitsSold,PublishDate,PublisherID,BookImage,IsSiteFeature,IsGenreFeature,BookStatusID")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookID = new SelectList(db.BookRoyalties, "BookID", "BookID", book.BookID);
            ViewBag.BookStatusID = new SelectList(db.BookStatuses, "BookStatusID", "BookStatusName", book.BookStatusID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", book.GenreID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherID);
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookID = new SelectList(db.BookRoyalties, "BookID", "BookID", book.BookID);
            ViewBag.BookStatusID = new SelectList(db.BookStatuses, "BookStatusID", "BookStatusName", book.BookStatusID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", book.GenreID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherID);
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookID,ISBN,BookTitle,Description,GenreID,Price,UnitsSold,PublishDate,PublisherID,BookImage,IsSiteFeature,IsGenreFeature,BookStatusID")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookID = new SelectList(db.BookRoyalties, "BookID", "BookID", book.BookID);
            ViewBag.BookStatusID = new SelectList(db.BookStatuses, "BookStatusID", "BookStatusName", book.BookStatusID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", book.GenreID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherID);
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC3Site.UI.MVC/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC3Site.DATA.EF;

namespace MVC3Site.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")] //--The link is hidden to ALL users except admin, so lock down ALL controller actions/views
    //by using the Authorize Attribute at the Controller level. This will secure ALL Actions in the controller.
    //See Books Controller for Multiple Role Access
    public class GenresController : Controller
    {
        private BookStorePlusEntities db = new BookStorePlusEntities();

        // GET: Genres
        public ActionResult Index()
        {
            return View(db.Genres.ToList());
        }

        // GET: Genres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // GET: Genres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GenreID,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Genres.Add(genre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        // GET: Genres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GenreID,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public ActionResult Delete(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);

            //logic to prevent url hacking to delete a record
            if (genre.Books.Count() == 0)
            {
                if (genre == null)
                {
                    return HttpNotFound();
                }
                return View(genre);
            }
            return RedirectToAction("Index");//This is where the request originates
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Genre genre = db.Genres.Find(id);
            db.Genres.Remove(genre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC3Site.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="keywords" content="Common words or themes in the site, matching up with content that appears in
          header tags also page/view name matchcing. - Keywords are comma separated inside this single set of quotes." />

    <meta name="description" content="This is the text that displays when your site is a returned result of a
          search.  Otherwise, the first 120 characters on the landing page are displayed as the description." />

    <meta name="author" content="Your Name Here" />

    <title>@ViewBag.Title | MVC3Site</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/Content/css/bootstrap.min.css" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/Content/css/style.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!--Datatables.net-->
    <link type="text/css" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    
    <!--MVCPaging Paged List CSS-->
    <link href="~/Content/PagedList.css" rel="stylesheet" />

    <!--jQueryUI Styles-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css" />
    
    <!--Custom Stylesheet - ALWAYS Last-->
    <link href="~/Content/CustomStyles.css" rel="stylesheet" />
    @RenderSection("DocumentHead", false)
</head>
<body>

    <!-- Header -->
    <header id="header" class="transparent-nav">
        <div class="container">
            <div class="navbar-header">
                <!-- Logo -->
                <div class="navbar-brand">
                    <a class="logo" href="@Url.Action("Index","Home")">
                        <img src="~/Content/img/centriq.png" height="200" alt="logo">
                    </a>
                </div>
                <!-- /Logo -->
                <!-- Mobile toggle -->
                <button class="navbar-toggle">
                    <span></span>
                </button>
                <!-- /Mobile toggle -->
            </div>

            <!-- Navigation -->
            <nav id="nav">
                <ul class="main-menu nav navbar-nav navbar-right">
                    <li><a @*class="selected"*@ href="@Url.Action("Index","Home")">Home</a></li>
                    <li><a href="@Url.Action("Index","Books")">Books</a></li>
                    <li><a href="@Url.Action("Index","Authors")">Authors</a></li>
                    <li><a href="@Url.Action("Index","Publishers")">Publishers</a></li>
                    <li><a href="@Url.Action("Index","Magazines")">Magazines</a></li>
                    @if (User.IsInRole("Admin"))
                    {

                        <li><a href="@Url.Action("Index","Genres")">Genres</a></li>
                        <li><a href="@Url.Action("Index","BookStatus")">Book Statuses</a></li>
                        <li>@Html.ActionLink("Roles", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("Users", "Index", "UsersAdmin")</li>
                    }
                    @if (Session["cart"] != null)
                    {

                        //total qty of items in the cart
                        var cart = (Dictionary<int, MVC3Site.UI.MVC.Models.ShoppingCartViewModel>)Session["Cart"];
                        var cartCount = cart.Sum(x => x.Value.Qty);

                        <li>
                            <a href="@Url.Action("Index","ShoppingCart")">
                                <i class="fa fa-shopping-cart"></i>
                                <sup><span class="cartCount">@cartCount</span></sup>
                            </a>
                        </li>
                    }

                    @Html.Partial("_LoginPartial")
                </ul>
            </nav>
            <!-- /Navigation -->

        </div>
    </header>
    <!-- /Header -->
    <!-- Home -->
    <div id="home" class="hero-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay"
             style="background-image:url(@Url.Content("~/Content/img/home-background.jpg"))"></div>
        <!-- /Backgound Image -->

        <div class="home-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h1 class="white-text">MVC3 Site</h1>
                        <p class="lead white-text">
                            MVC Review, Data Tables.net, Filtering and Paging, shopping cart,
                            AJAX, and more!
                        </p>
                        @*<a class="main-button icon-button" href="#">Get Started!</a>*@
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /Home -->
    <!--Main Section - RenderBody-->
    <div id="main" class="section">
        <div class="container">
            <div class="row">
                <!--This div is used for the AJAX Messaging associated with Publishers-->
                <div id="MessageDisplay">
                    <div class="col-md-10 col-md-offset-1" id="MessageContent"></div>
                </div>
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer id="footer" class="section">
        <!-- container -->
        <div class="container">
            <div id="bottom-footer" class="row">
                <!-- copyright -->
                <div class="footer">
                    <div class="footer-copyright">
                        <span>
                            &copy; Copyright @DateTime.Now.Year. All Rights Reserved. | This template is made with
                            <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a>
                        </span>
                        converted to MVC by <a href="http://www.kcappdev.net" target="_blank">KCAppDev.NET</a>
                    </div>
                </div>
                <!-- /copyright -->
            </div>
            <!-- row -->
        </div>
        <!-- /container -->
    </footer>
    <!-- /Footer -->
    <!-- preloader -->
    <div id='preloader'><div class='preloader'></div></div>
    <!-- /preloader -->
    <!-- jQuery Plugins -->
    <script type="text/javascript" src="~/Content/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Content/js/main.js"></script>

    <!--Datatables.net script-->
    <script type="text/javascript" src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

    <!--Ajax Script-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>

    <!--jQueryUI Script-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("scripts", required: false)
    <script>
        //highlight selected navigation - class setup in the custom.css
        $('.nav li a').each(function () {
            var fullAnchor = $(this).attr('href');
            var aController = fullAnchor.split('/');
            var fullPath = (window.location.pathname + location.search).substr(1);
            var pController = fullPath.split('/');
            //added for QueryString Search
            if (fullPath.indexOf('?') != -1) {
                pController = fullPath.split('?');
            }
            if (aController[1] == pController[0]) {
                $(this).addClass('selected');
            }
            //if the controller is Home, but the path does NOT match the ENTIRE anchor -remove
            //the class(prevents 2 nav elements from showing selected simultaneously)
            if (aController[1] == 'Home' && window.location.pathname != fullAnchor) {
                $(this).removeClass();
            }
            //Same for Register and Login
            if (aController[1] == 'Account' && window.location.pathname != fullAnchor) {
                $(this).removeClass();
            }
        });
    </script>

</body>
</html>

MVC3Site.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>